// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import Contact from './Contact/index.svelte';
import Resume from './Resume/index.svelte';
import Hero from './Hero/index.svelte';
import Interests from './Interests/index.svelte';
import Projects from './Projects/index.svelte';

export const components = {
	biography: Biography,
	contact: Contact,
	experience: Resume,
	hero: Hero,
	interests: Interests,
	projects: Projects
};
