// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import Resume from './Resume/index.svelte';
import Hero from './Hero/index.svelte';
import Interests from './Interests/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	biography: Biography,
	experience: Resume,
	hero: Hero,
	interests: Interests,
	rich_text: RichText
};
